swagger: "2.0"
info:
  version: "0.0.1"
  title: Nysset Slack Integration
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
#produces:
#  - application/json
paths:
  /slackrequest:
    # binds a127 app logic to a route
    x-swagger-router-controller: slack-request
    post:
      description: Request endpoint for accepting slash command from Slack
      operationId: slackRequest
      parameters:
        - name: command
          in: body
          required: true
          schema:
            $ref: '#/definitions/SlackCommand'

      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:

  SlackCommand:
    required:
      - token
      - text
      - response_url
    properties:
      token:
        type: string
      team_id:
        type: string
      team_domain:
        type: string
      channel_id:
        type: string
      channel_name:
        type: string
      user_id:
        type: string
      user_name:
        type: string
      command:
        type: string
      text:
        type: string
      response_url:
        type: string

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
